"""Tier-3 end-to-end tests exercising orchestrator → TrackingLLMAdapter → DB.

The LLM port is a ``FakeLLMPort`` injected via ``create_app(llm_factory=...)``;
the lifespan still wraps it in ``TrackingLLMAdapter`` exactly as it would the
real client. Each test queues responses, calls a public route, then queries
the DB directly to verify the recorded row(s).

LiteLLM-specific concerns (cost extraction, exception mapping) are covered
in ``tests/services/test_llm_client.py``; this suite is about wiring.
"""

from __future__ import annotations

import pytest
import sqlalchemy as sa

from qfa.adapters.db import llm_calls
from qfa.domain.errors import LLMError
from qfa.domain.models import LLMResponse
from tests.e2e.conftest import E2E_API_KEY

pytestmark = [pytest.mark.e2e, pytest.mark.asyncio]


async def _fetch_rows(e2e_engine):
    async with e2e_engine.connect() as conn:
        rows = (
            await conn.execute(sa.select(llm_calls).order_by(llm_calls.c.id.asc()))
        ).all()
    return rows


def _ok(text: str = "ok", cost: float = 0.0001) -> LLMResponse:
    return LLMResponse(
        structured=text,
        model="gpt-3.5-turbo",
        prompt_tokens=5,
        completion_tokens=2,
        cost=cost,
    )


class TestAnalyzeRecordsRow:
    async def test_post_analyze_records_one_ok_row_with_operation_analyze(
        self, e2e_client, e2e_fake_llm, e2e_engine
    ):
        """A successful /v1/analyze persists two ``ok`` rows — analyse + judge.

        The refactored Orchestrator.analyze makes two LLM calls: one for the
        main analysis (response_model=str) and one for the judge
        (response_model=AnalyzeJudgeResult).  Both are tracked individually by
        the TrackingLLMAdapter, so we expect two rows with operation=analyze
        and status=ok.
        """
        # Call 1: analysis text (response_model=str).
        e2e_fake_llm.queue_response(_ok(text="Analysis result text."))
        # Call 2: judge structured output.
        e2e_fake_llm.queue_response(
            _ok(
                text='{"quality_score": 0.8, "uncertainty_explanation": "Good coverage."}'
            )
        )

        resp = await e2e_client.post(
            "/v1/analyze",
            json={
                "feedback_records": [{"id": "d1", "text": "hello"}],
                "prompt": "summarize",
            },
            headers={"Authorization": f"Bearer {E2E_API_KEY}"},
        )
        assert resp.status_code == 200

        rows = await _fetch_rows(e2e_engine)
        assert len(rows) == 2
        for row in rows:
            assert row.operation == "analyze"
            assert row.status == "ok"
            assert row.error_class is None


class TestRequestIdEqualsCallId:
    """The X-Request-ID header value is persisted as ``llm_calls.call_id``.

    This is the unification contract: one UUID, generated by
    RequestIdMiddleware, surfaces both in the response header (and the
    response body's ``request_id``) and in every DB row produced by the
    request. Clients quoting an X-Request-ID can be looked up directly
    in the DB without log-grep gymnastics.
    """

    async def test_header_request_id_matches_persisted_call_id(
        self, e2e_client, e2e_fake_llm, e2e_engine
    ):
        """The UUID in X-Request-ID equals the call_id column of the inserted row.

        End-to-end proof that ``RequestIdMiddleware`` → ``call_scope_for``
        dependency → ``call_scope`` → ``LLMCallRecord.call_id`` all
        carry the same value.
        """
        from uuid import UUID

        # Two LLM calls: analysis text + judge structured output.
        e2e_fake_llm.queue_response(_ok(text="Analysis result text."))
        e2e_fake_llm.queue_response(
            _ok(
                text='{"quality_score": 0.8, "uncertainty_explanation": "Good coverage."}'
            )
        )

        resp = await e2e_client.post(
            "/v1/analyze",
            json={
                "feedback_records": [{"id": "d1", "text": "hello"}],
                "prompt": "summarize",
            },
            headers={"Authorization": f"Bearer {E2E_API_KEY}"},
        )
        assert resp.status_code == 200

        header_uuid = UUID(resp.headers["x-request-id"])
        body_request_id = UUID(resp.json()["request_id"])
        assert header_uuid == body_request_id

        rows = await _fetch_rows(e2e_engine)
        # Both the analyse call and the judge call are tracked; both share
        # the same call_id (the request UUID).
        assert len(rows) == 2
        assert all(r.call_id == header_uuid for r in rows)

    async def test_fanned_out_llm_calls_share_one_call_id_equal_to_request_id(
        self, e2e_client, e2e_fake_llm, e2e_engine
    ):
        """Two LLM calls under one request share the request's UUID.

        Guards the property #91's per-invocation aggregation depends on:
        every llm_calls row produced by a single HTTP request joins on
        the same UUID — which is also the X-Request-ID clients can see.
        """
        from uuid import UUID

        # /v1/summarize-aggregate fans out into 2 LLM calls: the aggregate
        # summary itself, then a judge call that scores the summary as a
        # plain float string. Queue both.
        e2e_fake_llm.queue_response(
            _ok(
                text='{"ids": ["d1"], "title": "t", "summary": "s", "quality_score": 0.5}'
            )
        )
        e2e_fake_llm.queue_response(_ok(text="0.9"))

        resp = await e2e_client.post(
            "/v1/summarize-aggregate",
            json={
                "feedback_records": [
                    {
                        "id": "d1",
                        "content": "hello",
                        "metadata": {
                            "created": "2024-06-01T12:00:00Z",
                            "feedback_record_id": "fi-d1",
                            "coding_level_1": "L1",
                            "coding_level_2": "L2",
                            "coding_level_3": "L3",
                        },
                    }
                ],
                "prompt": "summarize then aggregate",
            },
            headers={"Authorization": f"Bearer {E2E_API_KEY}"},
        )
        assert resp.status_code == 200

        header_uuid = UUID(resp.headers["x-request-id"])
        rows = await _fetch_rows(e2e_engine)
        assert len(rows) >= 2, "expected >=2 LLM calls for summarize-aggregate"
        assert {r.call_id for r in rows} == {header_uuid}


class TestAnalyzeFailureRecordsRow:
    async def test_llm_failure_records_error_row(
        self, e2e_client, e2e_fake_llm, e2e_engine
    ):
        e2e_fake_llm.queue_failure(LLMError("boom"))

        resp = await e2e_client.post(
            "/v1/analyze",
            json={
                "feedback_records": [{"id": "d1", "text": "hello"}],
                "prompt": "summarize",
            },
            headers={"Authorization": f"Bearer {E2E_API_KEY}"},
        )
        # The orchestrator converts LLMError → AnalysisError → 502.
        assert resp.status_code == 502

        rows = await _fetch_rows(e2e_engine)
        assert len(rows) == 1
        row = rows[0]
        assert row.operation == "analyze"
        assert row.status == "error"
        assert row.error_class == "LLMError"
        assert row.input_tokens == 0
        assert row.output_tokens == 0


class TestAssignCodesRecordsMultipleRows:
    async def test_one_request_records_multiple_rows_all_with_assign_codes(
        self, e2e_client, e2e_fake_llm, e2e_engine
    ):
        # The orchestrator walks Types → Categories → Codes one level at a
        # time, issuing both a "pick" (response_model=str, parsed as
        # ``{"selected": [<indices>]}``) and a "judge"
        # (response_model=JudgeResponse) call per level. With one
        # type/category/code path it issues 6 LLM calls in this order:
        # pick-Types, judge-Type, pick-Categories, judge-Category,
        # pick-Codes, judge-Code.
        coding_framework = {
            "types": [
                {
                    "name": "Type A",
                    "categories": [
                        {
                            "name": "Cat A1",
                            "codes": [{"code_id": "code-1", "name": "Code A1.1"}],
                        }
                    ],
                }
            ]
        }
        pick_response = '{"selected": [0]}'
        judge_response = '{"score": 0.9, "explanation": "fits well"}'
        for _ in range(3):
            e2e_fake_llm.queue_response(_ok(text=pick_response))
            e2e_fake_llm.queue_response(_ok(text=judge_response))

        resp = await e2e_client.post(
            "/v1/assign-codes",
            json={
                "coding_framework": coding_framework,
                "feedback_records": [{"id": "f1", "content": "some feedback text"}],
                "max_codes": 5,
            },
            headers={"Authorization": f"Bearer {E2E_API_KEY}"},
        )
        assert resp.status_code == 200

        rows = await _fetch_rows(e2e_engine)
        assert len(rows) == 6
        for row in rows:
            assert row.operation == "assign_codes"
            assert row.status == "ok"
