"""Tests for POST /v1/analyze — mode field validation and new response fields.

These tests are focused on the spec-117 additions (mode, quality_score,
uncertainty_explanation).  Pre-existing per-endpoint contract tests
(request_id, feedback_record_count, error handling) live in
test_routes.py::TestAnalyzeSuccess.
"""

import pytest

from qfa.domain.models import AnalysisResultModel

from .conftest import FAKE_API_KEY, FakeOrchestrator


def _auth_header(key=FAKE_API_KEY):
    return {"Authorization": f"Bearer {key}"}


def _valid_body(**overrides):
    """Return a minimal valid /v1/analyze request body."""
    body = {
        "feedback_records": [{"id": "r1", "text": "Water access was limited."}],
        "prompt": "What are the main themes?",
    }
    body.update(overrides)
    return body


class TestModeField:
    @pytest.mark.asyncio
    async def test_no_mode_field_defaults_to_single_pass_and_returns_200(self, client):
        """Omitting ``mode`` defaults to ``single_pass`` and the request succeeds.

        Backwards-compatibility guard: existing clients that do not send
        ``mode`` must not break after this change.
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(),
            headers=_auth_header(),
        )
        assert resp.status_code == 200

    @pytest.mark.asyncio
    async def test_explicit_single_pass_mode_returns_200(self, client):
        """Explicitly sending ``"mode": "single_pass"`` is valid and returns 200.

        Confirms the only currently-supported mode is accepted without error.
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(mode="single_pass"),
            headers=_auth_header(),
        )
        assert resp.status_code == 200

    @pytest.mark.asyncio
    async def test_hierarchical_mode_returns_200(self, client):
        """Sending ``"mode": "hierarchical"`` is valid and returns 200.

        Why: #124 adds hierarchical as a supported mode; the route must
        dispatch to ``analyze_hierarchical`` without a schema rejection.
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(mode="hierarchical"),
            headers=_auth_header(),
        )
        assert resp.status_code == 200

    @pytest.mark.asyncio
    async def test_unsupported_mode_returns_422(self, client):
        """Sending an unsupported ``mode`` value must return 422.

        Pydantic's ``Literal["single_pass", "hierarchical"]`` enforcement is
        the gate; this confirms the schema is wired into FastAPI validation.
        Only values outside the allowlist are rejected.
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(mode="batch"),
            headers=_auth_header(),
        )
        assert resp.status_code == 422


class TestResponseShape:
    @pytest.mark.asyncio
    async def test_quality_score_present_in_response(self, client):
        """``quality_score`` is present in the response on the happy path.

        May be ``null`` when the judge fails, but on the happy path the
        fake orchestrator returns a non-null score.
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(),
            headers=_auth_header(),
        )
        assert resp.status_code == 200
        data = resp.json()
        assert "quality_score" in data
        assert data["quality_score"] == 0.85

    @pytest.mark.asyncio
    async def test_uncertainty_explanation_present_in_response(self, client):
        """``uncertainty_explanation`` is present in the response on the happy path.

        Lets the analyst understand the judge's reasoning for the quality score.
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(),
            headers=_auth_header(),
        )
        assert resp.status_code == 200
        data = resp.json()
        assert "uncertainty_explanation" in data
        assert isinstance(data["uncertainty_explanation"], str)
        assert len(data["uncertainty_explanation"]) > 0

    @pytest.mark.asyncio
    async def test_quality_score_is_null_when_judge_fails(self, test_app):
        """``quality_score`` is ``null`` when the orchestrator signals judge failure.

        Simulates the judge-failure path by injecting an ``AnalysisResultModel``
        with ``quality_score=None`` directly via a custom orchestrator.
        The route must pass that ``None`` through to the client unchanged.
        """
        import httpx

        from qfa.services.prompts import JUDGE_UNAVAILABLE_EXPLANATION

        test_app.state.orchestrator = FakeOrchestrator(
            analyze_result=AnalysisResultModel(
                result="Disclaimer: Generated by AI. Human review required.\n\nSome analysis.",
                quality_score=None,
                uncertainty_explanation=JUDGE_UNAVAILABLE_EXPLANATION,
            )
        )

        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=test_app),
            base_url="http://test",
        ) as c:
            resp = await c.post(
                "/v1/analyze",
                json=_valid_body(),
                headers=_auth_header(),
            )

        assert resp.status_code == 200
        data = resp.json()
        assert data["quality_score"] is None
        assert data["uncertainty_explanation"] == JUDGE_UNAVAILABLE_EXPLANATION

    @pytest.mark.asyncio
    async def test_analysis_text_has_disclaimer_prefix(self, client):
        """The ``analysis`` field starts with the server-side disclaimer.

        The fake orchestrator returns an analysis with the disclaimer already
        prepended (matching production behaviour where the orchestrator does
        the prepend before returning).
        """
        resp = await client.post(
            "/v1/analyze",
            json=_valid_body(),
            headers=_auth_header(),
        )
        assert resp.status_code == 200
        analysis = resp.json()["analysis"]
        assert analysis.startswith(
            "Disclaimer: Generated by AI. Human review required."
        )
