#!/usr/bin/env bash
# Firewall for dev container — default-deny outbound, whitelist only
# necessary services via dnsmasq + ipset + iptables.
#
# How it works:
#   1. dnsmasq runs as the container's DNS resolver (localhost:53)
#   2. For every allowed domain, dnsmasq's --ipset option automatically adds
#      resolved IPs to the "allowed_ips" netfilter ipset on each DNS lookup
#   3. iptables allows outbound HTTPS only to IPs in the ipset
#   4. CDN IP rotation is handled naturally — each fresh DNS lookup updates
#      the ipset before the connection is attempted
#
# Belt-and-suspenders: GitHub CIDRs are fetched from their API and pre-seeded
# into the ipset, and an initial dig loop pre-seeds all allowed hosts too.
set -euo pipefail

# ── Allowed domains ──────────────────────────────────────────────────
ALLOWED_HOSTS=(
    # Claude Code (https://docs.anthropic.com/en/docs/claude-code/overview)
    api.anthropic.com
    claude.ai
    platform.claude.com
    sentry.io
    # Only the specific Sentry ingest subdomain used by Claude Code is listed.
    # DNS-based firewalls cannot do wildcard matching. Update this if the DSN changes.
    o4509477028462592.ingest.us.sentry.io
    statsig.anthropic.com
    statsig.com
    # GitHub
    github.com
    api.github.com
    objects.githubusercontent.com
    # Python package registries
    pypi.org
    files.pythonhosted.org
    # npm (for npx-based MCP servers)
    registry.npmjs.org
)

# ── Save upstream DNS before we overwrite resolv.conf ────────────────
UPSTREAM_DNS=$(grep -m1 '^nameserver' /etc/resolv.conf | awk '{print $2}')
if [ -z "$UPSTREAM_DNS" ]; then
    UPSTREAM_DNS="8.8.8.8"
    echo "Warning: no nameserver found in /etc/resolv.conf, falling back to $UPSTREAM_DNS"
fi
echo "Upstream DNS: $UPSTREAM_DNS"

# ── Create ipset (must exist before dnsmasq starts) ──────────────────
ipset create allowed_ips hash:net -exist
ipset flush allowed_ips

# ── Fetch CIDR ranges from services that publish them ────────────────
# DNS resolution misses IPs for services using load-balanced rotation.
# Fetch published ranges before applying firewall rules (outbound is
# still open at this point).
GITHUB_CIDRS=()
if meta=$(curl -sf --max-time 5 https://api.github.com/meta); then
    while IFS= read -r cidr; do
        GITHUB_CIDRS+=("$cidr")
    done < <(echo "$meta" | jq -r '(.web + .api + .git) | unique | .[] | select(test("^[0-9]+\\."))' 2>/dev/null)
    echo "Fetched ${#GITHUB_CIDRS[@]} GitHub CIDR ranges"
else
    echo "Warning: could not fetch GitHub IP ranges, falling back to DNS only"
fi

for cidr in "${GITHUB_CIDRS[@]}"; do
    ipset add allowed_ips "$cidr" -exist
done

# ── Pre-seed ipset via dig (belt-and-suspenders) ─────────────────────
for host in "${ALLOWED_HOSTS[@]}"; do
    for ip in $(dig +short "$host" 2>/dev/null | grep -E '^[0-9]+\.' || true); do
        ipset add allowed_ips "$ip" -exist
    done
done

echo "Pre-seeded ipset with $(ipset list allowed_ips | grep -c '^[0-9]') IPs"

# ── Generate dnsmasq config ──────────────────────────────────────────
DNSMASQ_CONF="/etc/dnsmasq.d/firewall-allowlist.conf"
mkdir -p /etc/dnsmasq.d

{
    echo "# Auto-generated by init-firewall.sh — do not edit"
    echo ""
    echo "# Upstream DNS server"
    echo "server=${UPSTREAM_DNS}"
    echo ""
    echo "# Don't read /etc/resolv.conf (we overwrite it to point to ourselves)"
    echo "no-resolv"
    echo ""
    echo "# Listen only on localhost"
    echo "listen-address=127.0.0.1"
    echo "bind-interfaces"
    echo ""
    echo "# Cache size"
    echo "cache-size=1000"
    echo ""
    echo "# Add resolved IPs for allowed domains to the ipset."
    echo "# Every DNS lookup for these domains automatically populates"
    echo "# the netfilter ipset, so CDN IP rotation is handled on the fly."
    for host in "${ALLOWED_HOSTS[@]}"; do
        echo "ipset=/${host}/allowed_ips"
    done
} > "$DNSMASQ_CONF"

# ── Start dnsmasq ────────────────────────────────────────────────────
# Kill any existing instance (container restart)
if pidof dnsmasq >/dev/null 2>&1; then
    killall dnsmasq 2>/dev/null || true
    sleep 0.5
fi

# Start as daemon. Use --conf-file to read only our config (not the
# default /etc/dnsmasq.conf which may have conflicting settings).
dnsmasq --conf-file="$DNSMASQ_CONF"
echo "dnsmasq started (upstream: $UPSTREAM_DNS)"

# ── Point container DNS to dnsmasq ───────────────────────────────────
echo "nameserver 127.0.0.1" > /etc/resolv.conf

# ── iptables rules ───────────────────────────────────────────────────
# Flush existing rules
iptables -F OUTPUT 2>/dev/null || true

# Allow loopback (container-internal + dnsmasq on localhost)
iptables -A OUTPUT -o lo -j ACCEPT

# Allow established/related connections (responses to allowed requests)
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow DNS only to the upstream resolver (dnsmasq forwards via localhost,
# but its upstream queries need to reach the real DNS server)
iptables -A OUTPUT -p udp --dport 53 -d "$UPSTREAM_DNS" -j ACCEPT
iptables -A OUTPUT -p tcp --dport 53 -d "$UPSTREAM_DNS" -j ACCEPT

# Allow connections to resolved whitelist IPs (HTTPS)
iptables -A OUTPUT -p tcp --dport 443 -m set --match-set allowed_ips dst -j ACCEPT

# Allow connections to Docker network (for database sidecars etc.)
# Detect the container's actual network subnet rather than allowing a broad range
DOCKER_SUBNET=$(ip route | grep -oP '172\.\d+\.\d+\.\d+/\d+' | head -1)
if [ -n "$DOCKER_SUBNET" ]; then
    iptables -A OUTPUT -d "$DOCKER_SUBNET" -j ACCEPT
else
    # Fallback: allow common Docker bridge range (narrower than /12)
    iptables -A OUTPUT -d 172.16.0.0/16 -j ACCEPT
fi

# Default deny everything else
iptables -A OUTPUT -j REJECT --reject-with icmp-port-unreachable

echo "Firewall initialized: dnsmasq + ipset with $(ipset list allowed_ips | grep -c '^[0-9]') pre-seeded IPs"
