name: CI

on:
  push:
#  pull_request:  # redundant with push
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install dependencies
        run: uv sync
      - name: ruff format
        run: uv run  ruff format --check src tests
      - name: ruff check
        run: uv run ruff check src tests
      - name: ty
        run: make ty
  docker-build:
    # build a docker image to test that it builds correctly.
    # Intentionally NOT pushing the image. That's a separate job ("release")..
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build Docker image (no push)
        run: docker build .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install dependencies
        run: uv sync
      - name: Run pytest
        run: uv run pytest
