name: evaluate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  assign-codes:
    uses: ./.github/workflows/evaluate-assign-codes.yaml
    permissions:
      contents: read
    secrets: inherit
